---
apiVersion: v1                 # API version of k8s for `StatefulSet`
kind: ServiceAccount           # Type of resource that we are creating
metadata:                      # Holds metadata for this resource
  name: rabbitmq               # Name of this resource
---
kind: Role                     # Type of resource that we are creating
apiVersion: rbac.authorization.k8s.io/v1beta1 # API version of k8s for `StatefulSet`
metadata:                      # Holds metadata for this resource
  name: rabbitmq-peer-discovery-rbac
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["endpoints"] #an endpoint in the Kubernetes API that stores a collection of API objects of a certain kind
  verbs: ["get"] #The actions on a resource that a role uses in its rules 
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"] #an endpoint in the Kubernetes API that stores a collection of API objects of a certain kind
  verbs: ["create"] #The actions on a resource that a role uses in its rules 
---
kind: RoleBinding             # Type of resource that we are creating
apiVersion: rbac.authorization.k8s.io/v1beta1 # API version of k8s for `StatefulSet`
metadata:                     # Holds metadata for this resource
  name: rabbitmq-peer-discovery-rbac
subjects:
- kind: ServiceAccount        # Type of resource that we are creating
  name: rabbitmq              # Name of this resource
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role                  # Type of resource that we are creating
  name: rabbitmq-peer-discovery-rbac # Name of this resource